<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-WindowsActivityLogger-305a5a4e-55ad-4b1a-a4e3-491b1cb46989</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="9.0.1" />
  </ItemGroup>
</Project>
